### ISSUE TITLE
npm install on Raspberry Pi (ARM Linux) fails

### ISSUE THREAD

**Issue by jyang** [node-webrtc/node-webrtc#118]
% npm install

> wrtc@0.0.20 install /home/jyang/src/node-webrtc
> node-pre-gyp install --fallback-to-build

node-pre-gyp http GET https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz
node-pre-gyp http 404 https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz
node-pre-gyp http Pre-built binary not available for your system (falling back to source compile with node-gyp) 
make: Entering directory `/home/jyang/src/node-webrtc/build'
  ACTION Run build script /dev/null
TARGET_ARCH=arm r5982 Release
Preparing directories ... done
Cloning depot tools ... error (see build.log for details): make: *** [/dev/null] Error 255
make: Leaving directory`/home/jyang/src/node-webrtc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jyang/src/node-webrtc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.10.19+
gyp ERR! command "/opt/node-v0.10.26-linux-arm-pi/bin/node" "/home/jyang/src/node-webrtc/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=wrtc" "--configuration=Release" "--module_name=wrtc" "--version=0.0.20" "--patch=20" "--runtime=node" "--node_abi=node-v11" "--platform=linux" "--arch=arm" "--target_arch=arm" "--module_main=lib/index.js" "--host=https://wrtc-binaries.s3.amazonaws.com/" "--module_path=/home/jyang/src/node-webrtc/lib/binding" "--remote_path=./wrtc/v0.0.20/Release/" "--package_name=wrtc-v0.0.20-node-v11-linux-arm.tar.gz" "--staged_tarball=build/stage/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz" "--hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/" "--hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz"
gyp ERR! cwd /home/jyang/src/node-webrtc
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/opt/node-v0.10.26-linux-arm-pi/bin/node rebuild --name=wrtc --configuration=Release --module_name=wrtc --version=0.0.20 --patch=20 --runtime=node --node_abi=node-v11 --platform=linux --arch=arm --target_arch=arm --module_main=lib/index.js --host=https://wrtc-binaries.s3.amazonaws.com/ --module_path=/home/jyang/src/node-webrtc/lib/binding --remote_path=./wrtc/v0.0.20/Release/ --package_name=wrtc-v0.0.20-node-v11-linux-arm.tar.gz --staged_tarball=build/stage/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz --hosted_path=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/ --hosted_tarball=https://wrtc-binaries.s3.amazonaws.com/wrtc/v0.0.20/Release/wrtc-v0.0.20-node-v11-linux-arm.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/jyang/src/node-webrtc/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:743:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
node-pre-gyp ERR! System Linux 3.10.19+
node-pre-gyp ERR! command "node" "/home/jyang/src/node-webrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/jyang/src/node-webrtc
node-pre-gyp ERR! node -v v0.10.26
node-pre-gyp ERR! node-pre-gyp -v v0.5.13
node-pre-gyp ERR! not ok 

npm ERR! wrtc@0.0.20 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.20 install script.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.10.19+
npm ERR! command "/opt/node/bin/node" "/opt/node/bin/npm" "install"
npm ERR! cwd /home/jyang/src/node-webrtc
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jyang/src/node-webrtc/npm-debug.log
npm ERR! not ok code 0
npm install  29.60s user 1.36s system 88% cpu 34.998 total

**Comment by mschrupp** [comment]
fails for me too on an RPi with Raspbian.
Git-Checkout, bin/build.js works on if I clone depot_tools manually from git.

bin/install.js will fail with architecture: arm not supported

No chance I can get this running on my RPi? I hope there is =(

**Comment by modeswitch** [comment]
I haven't added ARM support yet, but it should be possible.

**Comment by modeswitch** [comment]
This should work now.

**Comment by ghost** [comment]
Hi,
Just tried to install via npm on raspberry pi. Still fails. Are there any tricks?

**Comment by modeswitch** [comment]
@kompsale Can you share some more details? Error messages would be helpful.

**Comment by ghost** [comment]
Sure. This is my log below:

# 

pi@raspberrypi ~/nodefiles $ sudo npm install wrtc
\

> wrtc@0.0.55 install /home/pi/nodefiles/node_modules/wrtc
> node-pre-gyp install --fallback-to-build

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/nodefiles/node_modules/wrtc/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: node-v0.12.0.tar.gz local checksum 4f93d284348af976ff9ccb3bcf0bc3078f51f8ddc92a7bc14b62f2851b09c37a not match remote 9700e23af4e9b3643af48cef5f2ad20a1331ff531a12154eef2bfb0bb1682e32
gyp ERR! stack     at deref (/home/pi/nodefiles/node_modules/wrtc/node_modules/node-gyp/lib/install.js:299:20)
gyp ERR! stack     at IncomingMessage.<anonymous> (/home/pi/nodefiles/node_modules/wrtc/node_modules/node-gyp/lib/install.js:340:13)
gyp ERR! stack     at IncomingMessage.emit (events.js:129:20)
gyp ERR! stack     at _stream_readable.js:908:16
gyp ERR! stack     at process._tickCallback (node.js:355:11)
gyp ERR! System Linux 3.18.7+
gyp ERR! command "/usr/local/bin/node" "/home/pi/nodefiles/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm/wrtc.node" "--module_name=wrtc" "--module_path=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm" "--python=python2"
gyp ERR! cwd /home/pi/nodefiles/node_modules/wrtc
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/pi/nodefiles/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm/wrtc.node --module_name=wrtc --module_path=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm --python=python2' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/nodefiles/node_modules/wrtc/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Linux 3.18.7+
node-pre-gyp ERR! command "node" "/home/pi/nodefiles/node_modules/wrtc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/nodefiles/node_modules/wrtc
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /home/pi/nodefiles/node_modules/wrtc/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm/wrtc.node --module_name=wrtc --module_path=/home/pi/nodefiles/node_modules/wrtc/build/wrtc/v0.0.55/Release/node-v14-linux-arm --python=python2' (1)
npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "wrtc"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.55 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wrtc@0.0.55 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/nodefiles/npm-debug.log

# pi@raspberrypi ~/nodefiles $

**Comment by 3du4** [comment]
I had same problem but updating to the newest node version problem solved.

**Comment by anuradhawick** [comment]
@3du4 Can you tell me your npm version and node version. I get the same set of errors and cannot compile on ARM (Banana Pi M3). Would you mind sharing prebuilt node module for ARM if thats possible. Thanks

**Comment by 3du4** [comment]
@anuradhawick this has been over a year. I can't recall what npm version I had at that time. If you want to try different versions try using nvm.

https://github.com/creationix/nvm

**Comment by dulajra** [comment]
@anuradhawick You can compare the comment date of @3du4 with [Node release dates](https://nodejs.org/en/download/releases/). Try nearest versions of node
