### ISSUE TITLE
possible CPU leak

### ISSUE THREAD

**Issue by max-mapper** [node-webrtc/node-webrtc#201]
Hi, apologies for not having a better reproducible test case here.

I was testing using wrtc on ubuntu, and after about an hour or two I noticed my process was using 100% of CPU. It was completely pegging it, but it was pretty close.

This was running https://github.com/moose-team/friends/blob/7dc1fd6dbc5748341a669c1e5e3c41729a1eb8e4/cli.js

The above is a script that connects to a rtc peer swarm using only data channels. In my case it was connected to between 10-15 peers with very low bandwidth (a few kb per message, with 1-2 messages a minute).

Just wanted to leave a heads up. I've switched to running my code inside electron headlessly on ubuntu, since webrtc "just works" there, and I haven't hit any CPU issues yet.

**Comment by modeswitch** [comment]
Yikes, that sounds bad. A test case would really help here.

**Comment by max-mapper** [comment]
Hey we made some progress on this and found a bug in libjingle, turns out it isnt in `wrtc`! I'll link the libjingle issue when we finish making it

**Comment by modeswitch** [comment]
Cool. We've already had to lift a few patches from upstream, so I don't foresee a problem here.

**Comment by max-mapper** [comment]
actually found two bugs, here is the first one: https://code.google.com/p/webrtc/issues/detail?id=4621&thanks=4621&ts=1430795884#makechanges

**Comment by rom1504** [comment]
I'm seeing the same thing letting https://github.com/feross/webtorrent-hybrid (which use wrtc)  run for a few hours in seeding mode.

**Comment by beaugunderson** [comment]
this was just fixed upstream: https://code.google.com/p/webrtc/issues/detail?id=4621

**Comment by modeswitch** [comment]
@beaugunderson Is there anything more in the upstream patch that should be merged here?

**Comment by beaugunderson** [comment]
@modeswitch i think the patchset should be merged into libwebrtc (if i understand how node-webrtc and libwebrtc relate to chromium) but i don't understand "anything more in the upstream patch" :)

**Comment by rom1504** [comment]
see https://github.com/js-platform/libwebrtc/pull/11 ;)

**Comment by beaugunderson** [comment]
oh, hadn't seen that! then yes, definitely; sometimes `pings_since_last_response_` grows to contain 700,000+ entries and I believe that's also fixed in the patchset linked to in [upstream #4621](https://code.google.com/p/webrtc/issues/detail?id=4621)

**Comment by rom1504** [comment]
yeah but there's probably still some things to take from that upstream patch because it seems https://github.com/js-platform/libwebrtc/pull/11 didn't fix the issue entirely, I'm still getting cpu leaks using (an updated) webtorrent-hybrid

**Comment by beaugunderson** [comment]
yes, i agreed above that the rest of the patch is necessary :)

**Comment by modeswitch** [comment]
That's what I suspected. Might be best then to revert the patch I just merged and make a PR for the upstream patch. Can one of you do this?

**Comment by Stiveknx** [comment]
There's any update on this issue?
I depend on wrtc for some projects, this fix would help.

**Comment by gev** [comment]
Like still actual problem! have 100% CPU usage on raspbian baster and node 12 LTS
